apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner-watcher.fullname" . }}
  labels:
    {{- include "runner-watcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runner-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runner-watcher.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runner-watcher.serviceAccountName" . }}
      securityContext:
        fsGroup: 1337
      containers:
        - name: controller-manager
          command:
          - /manager
          args:
          - --webhook-url={{ .Values.webhook.url }}
          - --webhook-events={{ .Values.webhook.events | join "," }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
          - containerPort: 8443
            name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end}}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
